//-- Params
const BG_COLOR = '#020008';
const NUM_STARS = 1200;
const MAX_SPEED = 2;
const MIN_DURATION = 5;
const MAX_DURATION = 20;
const MAX_SIZE = 1;
const MAX_PARALLAX_SPEED_MODIF = 2;
const PARALLAX_SPEED_CHANGE_RATE = 5;